### ISSUE TITLE
Investigate resource usage of cellxgene on Oscar

### ISSUE THREAD

**Issue by nictru** [Mye-InfoBank/SIMBA#15]
Apparently Oscar crashed during a conference when more than 10 users were using the service at the same time. We should check the RAM usage test-wise in order to determine if we can host the datasets at the WZW or not.

**Comment by alex-d13** [comment]
Check out alternative solutions, where we can host cellxgene / upload our atlas:

Apparently, cellxgene has an option to upload datasets: https://cellxgene.cziscience.com/datasets

There are a few requirements we have to check if we want to use this service: https://cellxgene.cziscience.com/docs/032__Contribute%20and%20Publish%20Data 
I am not sure if they accept atlas-type datasets, as this is no 'novel' dataset, but a collection of existing datasets. We might have to check if other atlas-type datasets are uploaded there already.

**Comment by nictru** [comment]
After changing the output storage format to sparse CSC-matrices, running the DGE analysis between 180k and 130k cells used 2 cores at 100% for 70s. Then it finished successfully. Will check with multiple instances simultanously later on, since my laptop alone was not powerful enough.

**Comment by nictru** [comment]
A test with 5 simultanious runs also showed solid performance. Most probably, the switch to CSC sparse matrices solved it.
