### ISSUE TITLE
Implement clustering QC analysis

### ISSUE THREAD

**Issue by nictru** [Mye-InfoBank/SIMBA#24]
Recently, @alex-d13 presented a paper for analysis of cluster-trustworthyness. This can help the experts with identifying the best suited clustering resolution for their use case.

@alex-d13, if you can provide me with an example script or documentation on how to use the tool, I can add it to the pipeline.

**Comment by alex-d13** [comment]
This is the GH repo: https://github.com/igrabski/sc-SHC and the paper https://doi.org/10.1038/s41592-023-01933-9.

Briefly, for each cluster-split it performs a hypothesis test, whether this split is significant. Can be run as a standalone clustering method, or can be performed on top of an existing clustering.

**Comment by nictru** [comment]
According to [this issue](https://github.com/igrabski/sc-SHC/issues/3), only count data can be processed. Since we heavily rely on integration methods for batch correction which only deliver embeddings, this tool might not be optimal for our use case.

**Comment by nictru** [comment]
I added some information about the quality of the sc-SHC results in #29.

Since I don't think that this package is optimal for our use case, I am thinking about using one of the methods mentioned in [this paper](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-022-02622-0#:~:text=Intra%2D%20and%20inter%2Dcluster%20similarity%20is,under%20the%20suboptimal%20number%20of%20clusters.)
