### ISSUE TITLE
Switch to hard threshold of minimum cells to keep a gene

### ISSUE THREAD

**Issue by nictru** [Mye-InfoBank/SIMBA#40]
Discussed with @FPetitprez 

Goal is to keep genes which are only expressed in a very low number of absolute cells in large atlasses

**Comment by nictru** [comment]
Should be a pipeline parameter, but we should think of a good default 50

**Comment by alex-d13** [comment]
We would also need this feature for the enteroendocrine atlas, where many genes are only expressed in a small number of cells. Has the option of a whitelist also been discussed already?

**Comment by nictru** [comment]
Not yet, but can easily be done

Actually we could evaluate if such a filter is useful at all, since currently it is still an artifact from the time when all the genes went through all the pipeline processes. Since we are handling this differently now (the dataset with all genes is only passed through the counts branch, all other processes use gene intersection) the influence on the pipeline performance, memory and space requirements might be drastically lower than when I implemented this filter.
