### ISSUE TITLE
Write a how-to guide for dataset pre-processing

### ISSUE THREAD

**Issue by FPetitprez** [Mye-InfoBank/SIMBA#8]
We need a guide to specify how to prepare the datasets for input into the pipeline.

**Comment by nictru** [comment]
The data format is now pretty much covered in the SIMBA readme. However, batch annotation best practices should be added (already outlined in the STSM-preprocessing repo).

**Comment by nictru** [comment]
Done via [here](https://github.com/Mye-InfoBank/SIMBA/wiki/Dataset-preparation)
